spring:
  application:
    name: google-ai
  ai:
    openai:
      api-key: ${OPEN-AI-KEY}
      chat:
        options:
          model: gpt-4o
weather:
  api-key:${WEATHER_API_KEY}
  api-url:http://api.weatherapi.com/v1


#    vertex:
#      ai:
#        gemini:
#          project-id: Gemini API
#          location: us-central1
#          chat:
#            options:
#                model: gemini-2.0-flash-001



